<h1>Statusses</h1>

<a href='<?php echo $this->url(
    array(
        'controller' => 'upload',
        'action'     => 'process',
    ), 
    'default', 
    true) ?>'>Do processing (background job) run</a>
    
<?php foreach($this->works as $work): ?>
<div class="work" style='clear: both'>
<b>Attachment: <?php echo $work->file_id?>, Filename: <?php echo $this->escape($work->file_name)?>, File mimetype: <?php echo $this->escape($work->file_mimetype)?></b>
<?php if(!is_null($work->thumbnail_file_name)): ?>
<img src="/thumbnails/<?php echo $this->escape($work->thumbnail_file_name)?>" alt="thumbnail" width="200" style="float:right">
<?php endif; ?>
<table>
  	<tr>
  		<td>action</td>
  		<td>start</td>
  		<td>end</td>
  		<td>finished?</td>
  		<td>success?</td>
  		<td>message</td>
  	
  	</tr>
  <?php foreach($work->StatusLines as $line):?>
  	<tr>
  		<td>
  			<?php if($line->result_url != null): ?>
  			<a href="<?php echo $line->result_url?>">
  			<?php endif;?>
  			<?php echo $this->escape($line->action)?>
  			
  			
  			<?php if($line->result_url != null): ?></a><?php endif;?>
  		</td>
  		<td><?php echo $this->escape($line->event_start)?></td>
  		<td><?php echo $this->escape($line->event_end)?></td>
  		<td><?php echo $line->finished?"Finished":"In Progress"?></td>
  		<td><?php echo $line->finished?($line->success?"Success":"Fail"):""?></td>
  		<td><?php echo $this->escape($line->message)?></td>
  	
  	</tr>
  
  <?php endforeach;?>


</table>




</div>


<?php endforeach; ?>