<h1>Statusses</h1>

<?php foreach($this->works as $work): ?>
<div class="work">
<b>Attachment: <?php echo $work->attachment_id?>, Filename: <?php echo $this->escape($work->file_name)?>, File mimetype: <?php echo $this->escape($work->file_mimetype)?></b>
<img src="/thumbnails/<?php echo $this->escape($work->file_name)?>" alt="thumbnail" width="200" style="float:right">
<table>
  	<tr>
  		<td>action</td>
  		<td>start</td>
  		<td>end</td>
  		<td>finished?</td>
  		<td>success?</td>
  		<td>message</td>
  	
  	</tr>
  <?php foreach($work->StatusLines as $line):?>
  	<tr>
  		<td><?php echo $this->escape($line->action)?></td>
  		<td><?php echo $this->escape($line->event_start)?></td>
  		<td><?php echo $this->escape($line->event_start)?></td>
  		<td><?php echo $line->finished?"Finished":"In Progress"?></td>
  		<td><?php echo $line->finished?($line->success?"Success":"Fail"):""?></td>
  		<td><?php echo $this->escape($line->message)?></td>
  	
  	</tr>
  
  <?php endforeach;?>


</table>




</div>


<?php endforeach; ?>