<h1>A test token</h1>

<a href='<?php echo $this->url(
    array(
        'controller' => 'upload',
        'action'     => 'index',
    	'filetype'	 => $this->filetype,
    	'attachmentid' => $this->attachmentId,
    	'timestamp' => $this->timestamp,
    	'token'		=> $this->token,
    	'return_element' => 'none',
    	'return_url' => 'none'
    ), 
    'default', 
    true) ?>'>Fill form with a bogus attachment id</a>