<ul>
<?php foreach($this->messages as $message):?>
	<li><?php echo $message ?></li>
<?php endforeach;?>
</ul>
Username: <?php echo $this->escape($this->user->username) ?><br />
Name: <?php echo $this->escape($this->user->fullname) ?> | <?php echo $this->user->fullname ?><br />
<br />
Balance: <?php echo $this->user->transactionBalance ?> (<a href="<?php echo $this->url(
    array(
        'controller' => 'user',
        'action'     => 'transactionhistory',
    	'id'		=> $this->user->id
    ), 
    'default', 
    true) ?>">Transaction history</a>)<br />
<br />
<?php if(count($this->user->activeReservations) > 0):?>
	<h2>Current Terminal Reservation<?php if(count($this->user->activeReservations) > 0) echo "s"?></h2>
	<table>
	<?php foreach($this->user->activeReservations as $reservation):?>
	<tr><td><?php echo $this->escape($reservation->terminalName) ?></td><td><?php echo $reservation->startDate ?></td><td><?php echo $reservation->endDate ?></td></tr>
		
	<?php endforeach;?>
	</table>

<?php endif;?>


<h3>Enrolments</h3>
<table>
<?php foreach($this->enrolments as $enrolment):?>
<tr><td><?php echo $this->escape($enrolment->course->name) ?></td><td><?php echo $this->escape($enrolment->enrolmentDate) ?></td><td>
<a href="<?php echo $this->url(
    array(
        'controller' => 'lesson',
        'action'     => 'register',
    	'enrolment'		=> $enrolment->id
    ), 
    'default', 
    true) ?>">Register Lesson</a></td>
    <td><a href="<?php echo $this->url(
    array(
        'controller' => 'course',
        'action'     => 'finish',
    	'id'		=> $enrolment->id
    ), 
    'default', 
    true) ?>">Finish Enrolment</a></td></tr>
<?php endforeach?>
</table>

<h3>Previous Enrolments</h3>
<table>
<?php foreach($this->finishedEnrolments as $enrolment):?>
<tr><td><?php echo $this->escape($enrolment->course->name) ?></td><td><?php echo $this->escape($enrolment->enrolmentDate) ?></td><td><a href="<?php echo $this->url(
    array(
        'controller' => 'course',
        'action'     => 'enroll',
    	'user'		=> $this->user->id,
    	'course'	 => $enrolment->course->id
    ), 
    'default', 
    true) ?>">Enroll again</a></td></tr>
<?php endforeach?>
</table>

<h3>Courses</h3>
<?php foreach($this->unEnrolledCourses as $course):?>
<?php echo $this->escape($course->name) ?> <a href="<?php echo $this->url(
    array(
        'controller' => 'course',
        'action'     => 'enroll',
    	'user'		=> $this->user->id,
    	'course'	 => $course->id
    ), 
    'default', 
    true) ?>">Enroll</a><br />
<?php endforeach?>



<a href="<?php echo $this->url(
    array(
        'controller' => 'user',
        'action'     => 'index'
    ), 
    'default', 
    true) ?>">Index</a>