<?php if($this->successUpload):?>
<h1>Success</h1>
<p>The file you selected is successfully uploaded. This file will be processed in the background and putted into the Sponsorship system. This can take a while. The status you can find on <a href='<?php echo $this->url(
    array(
        'controller' => 'upload',
        'action'     => 'status',
    	'correlationid' => $this->correlationId,
    ), 
    'default', 
    true) ?>'>this page</a>.</p>
    
    <p> You can close this window, this will not affect the processing of the file.</p>

<?php else:?>
<h1>Uploader</h1>
<?php echo $this->form ?>

<?php endif;?>
