<?php 
$this->jQuery()
       ->enable()
       ->addJavascriptFile('/js/jquery.ba-postmessage.min.js')
       ->addJavascriptFile('/js/jquery.form.js')
       ->addOnload("
          var return_url = '".$this->escape($this->return_url)."';
		  var return_element = '". $this->escape($this->formActionParams['return_element']) ."';
		  var file_id = ".$this->escape($this->formActionParams['file_id']).";
         ")
       
       ->addOnload("
         $('#cancel').click(
            function(event){
              	$.postMessage(
	                return_element + '||',
	                return_url,
	                parent
	            );
              event.preventDefault();
            
            }
         );
       
       ")
       ->addOnload("
          $('#uploadform').ajaxForm({ 
            dataType:  'xml',
            success: function(responseXML) {
              var success = $('success', responseXML).text();
              var filename = $('filename', responseXML).text();
              var message = $('message', responseXML).text(); 
			  if(success == 'true') {
			   
			  	$.postMessage(
	                return_element + '|' + file_id + '|' + filename,
	                return_url,
	                parent
	            );
			  } else {
			  	$('#error_message').html(message);
			  }
            }
          }); 
         ")
       ;
?>

<h1>Uploader</h1>
<span id="error_message" style="color:red"></span>
<?php $this->form->setAction($this->url($this->formActionParams));
echo $this->form ?>