<h1>Uploaded</h1>
<p>The file you selected is successfully uploaded. This file will be processed in the background and putted into the Sponsorship system. This can take a while. The status you can find on <a href='<?php echo $this->url(
    array(
        'controller' => 'upload',
        'action'     => 'status',
    	'correlationid' => $this->correlationId,
    ), 
    'default', 
    true) ?>'>this page</a>.</p>
    
    <script type="text/javascript">
		var filename = "<?php echo $this->escape($this->filename) ?>";
		var return_url = "<?php echo $this->escape($this->return_url) ?>";
		var return_element = "<?php echo $this->escape($this->return_element) ?>";
	</script>
	<p>Filename: <?php echo $this->escape($this->filename) ?></p> 
    <a href="" class="return_modal">Attach this file</a> <a href="" class="cancel_modal">Cancel</a>