<?php echo $this->doctype()?>
<html>

   <head>
      <title>SwitchedOn: Upload Agent</title>
      <?php echo $this->jQuery() ?>
      <!--  <script type="text/javascript" src="js/jquery-1.3.2.min.js"></script>
	  <script type="text/javascript" src="js/jquery.ba-postmessage.min.js"></script>
      <script type="text/javascript">
		$(document).ready(function(){
		    $(".cancel_modal").click(
		        function(event){
			        $.postMessage(
		                return_element + '|' + '',
		                return_url,
		                parent
		            );
		            event.preventDefault();
		        }
		    );
		
		});

		$(document).ready(function(){
		    $(".return_modal").click(
		        function(event){
			        $.postMessage(
		                return_element + '|' + filename,
		                return_url,
		                parent
		            );
		            event.preventDefault();
		        }
		    );
		
		});
		
	  </script>-->
   </head>
   
   <body>
   		
		<?php echo $this->layout()->content ?>
   
   </body>
   
   
   
</html>