Username: <?php echo $this->escape($this->user->username) ?><br />
Name: <?php echo $this->escape($this->user->fullname) ?><br />
<br />
Balance: <?php echo $this->user->transactionBalance ?><br />
<br />

<h2>Payment History</h2>
<table>
<tr><td>Description</td><td>Date</td><td>Cost</td><td>Payment</td></tr>
<?php foreach($this->historylines as $entry):?>
	<tr>
		<td><?php echo $this->escape($entry->description) ?></td>
		<td><?php echo $this->escape($entry->date->toString(null,$locale)) ?></td>
		<td style='color: #FF0000;'><?php echo $this->escape($entry->cost) ?></td>
		<td style='color: #00FF00;'><?php echo $this->escape($entry->payment) ?></td>
	
	 </tr>

<?php endforeach;?>
</table>
<br>
User balance: <?php echo $this->user->transactionBalance?> <br />