Username: <?php echo $this->escape($this->user->username) ?><br />
Name: <?php echo $this->escape($this->user->fullname) ?><br />
<br />
Balance: <?php echo $this->user->transactionBalance ?> (<a href="<?php echo $this->url(
    array(
        'controller' => 'user',
        'action'     => 'transactionhistory',
    	'id'		=> $this->user->id
    ), 
    'default', 
    true) ?>">Transaction history</a>)<br />
<br />

<h3>Enrolments</h3>
<table>
<?php foreach($this->enrolments as $enrolment):?>
<tr><td><?php echo $this->escape($enrolment->course->name) ?></td><td><?php echo $this->escape($enrolment->enrolmentDate) ?></td><td>
<a href="<?php echo $this->url(
    array(
        'controller' => 'lesson',
        'action'     => 'register',
    	'enrolment'		=> $enrolment->id
    ), 
    'default', 
    true) ?>">Register Lesson</a></td></tr>
<?php endforeach?>
</table>

<h3>Courses</h3>
<?php foreach($this->unEnrolledCourses as $course):?>
<?php echo $this->escape($course->name) ?> <a href="<?php echo $this->url(
    array(
        'controller' => 'course',
        'action'     => 'enroll',
    	'user'		=> $this->user->id,
    	'course'	 => $course->id
    ), 
    'default', 
    true) ?>">Enroll</a><br />
<?php endforeach?>



<a href="<?php echo $this->url(
    array(
        'controller' => 'user',
        'action'     => 'index'
    ), 
    'default', 
    true) ?>">Index</a>