#!/bin/sh
#
# installer
#
# Copyright (c) 2009, Switched On
#
# Install script for updating and configuring a base OpenSUSE 11.1 
# installation to make it a "Switched On" machine.
#
#



#==================
# Install packages
#==================
# Check file exists
# if not, assume no packages and continue
# loop through each line of the file
# if the line does not begin with # and is not blank, then
# install that package
file=packages
if [ -f $file ]
then
  x=0
  while [ $x -lt $(wc -l < $file) ]
  do
    let x=x+1
    line=`head -n $x $file | tail -n 1`
    case "$line" in
      "") ;;
      \#*) ;;
      * ) 
          echo "Installing $line..."
          zypper -n install $line
          ;;
    esac
  done
fi

