options:
  type: INNODB
  collate: utf8_general_ci
  charset: utf8

Work:
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    file_id: 
      type: integer
      notnull: true
    form_pending_id:
      type: integer
      notnull: true
    title: string(300)
    description: string(500)
    file_name: 
      type: string(300)
      notnull: true
    file_type: 
      type: enum
      values: [image, video]
      notnull: true
    file_mimetype: string(100)
    file_service_id: string(20)
    current_pid:
      type: integer
    finished:
      type: boolean
      default: false
      notnull: true
  relations:
    StatusLines:
      class: StatusLine
      foreign: work_id
      local: id
      type: many

StatusLine:
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    work_id: 
      type: integer
      notnull: true
    process_id: 
      type: integer
      notnull: true
    action:
      type: enum
      values: [media_received, create_thumbnail, convert, upload, report]
      notnull: true
    event_start: 
      type: timestamp
      notnull: true
    event_end: timestamp
    finished:
      type: boolean
      default: false
      notnull: true
    success: 
      type: boolean
      default: false
      notnull: true
    message: string(300)
  relations:
    Work:
      local: work_id
      foreign: id

