<?php 
echo $this->doctype() ?>
<html>

   <head>
      <title>SwitchedOn: User Manager</title>
	<meta http-equiv="Content-Language" content="English" />
	<meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
	<meta name="author" content="SwitchedOn" />
	<meta name="description" content="Empowering ethically through IT" />
	<meta name="keywords" content="switchedon, switched, on, IT, computer, internet, underprivileged, ethically" />	
	<meta name="Robots" content="index,follow" />
	<?php echo $this->headLink()->appendStylesheet('/styles/sousermgr.css') ?>
	

   </head>

   <body>        
   		<div id="container">

            <div id="container-header">
                <div id="container-name"><span>Switched</span>On</div>
		<div id="container-slogan">User Manager</div>
            </div>
            
	    <div id="container-eyecatcher">
                <div id="container-navigation"><ul id="navigation">
                <li><a href="<?php echo $this->url(
    array(
        'controller' => 'index',
        'action'     => 'index'
    ), 
    'default', 
    true) ?>">Home</a></li>
                <li><a href="<?php echo $this->url(
    array(
        'controller' => 'user',
        'action'     => 'index'
    ), 
    'default', 
    true) ?>">Users</a></li>
                <li><a href="<?php echo $this->url(
    array(
        'controller' => 'course',
        'action'     => 'index'
    ), 
    'default', 
    true) ?>">Courses</a></li>
                <li><a href="<?php echo $this->url(
    array(
        'controller' => 'terminal',
        'action'     => 'index'
    ), 
    'default', 
    true) ?>">Terminals</a></li>
                <li><a href="#">Logout</a></li>
                </ul></div>
            <img src="<?php echo $this->baseUrl('images/SO_eyecatcher.jpg'); ?>" alt="SwitchedOn picture" />
	    </div>

            <div id="container-content">

		<div id="content">
   <?php echo $this->layout()->content ?>
</div> <!-- CONTENT END -->

		<div id="border">
			<h4>More About Us</h4>
			<ul id="subnavigation">
				<li><a href="http://www.switchedon.org/">SwitchedOn</a></li><!--<li><a href="#">Link to a subpage 2</a></li><li><a href="#">Link to a subpage 3</a></li>-->
			</ul>
			<hr />

			<h4>Latest News</h4>
			<ul id="news">
				<li>This is a beta site</li>
				<li>Produced at the SwitchedOn Developer workship</li>
				<li>04/04/09</li>
			</ul>

			<hr />

			<h4>Our Address</h4>
			<p>Switched On (International)<br />
3 Cranborne Chase<br />
IPSWICH<br />
IP4 3EQ<br />
England<br /><br />

Registered charity No:<br />1116769<br /><br />
				
Registered company No:<br />5907599<br /><br />

				
E-Mail: <a href="mailto:admin@switchedon.org">admin@switchedon.org</a>
			</p>

		</div>

	    </div>

            <div id="container-footer">
                 <div id="footer">
                    <div id="footer-copyright">&copy; 2009 switchedon.org - all rights reserved. <a href="#">Terms of use</a></div><div id="footer-meta"><a href="http://validator.w3.org/check?uri=referer">XHTML</a> | <a href="http://jigsaw.w3.org/css-validator/check/referer">CSS</a> | <a href="http://www.christian-pansch.de" title="Webdesign Bremen">Design by christian-pansch.de</a> </div></div>
            </div>

        </div> <!-- ENDE container -->
   </body>
</html>
   