<?php

/**
 * Work
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Work extends BaseWork
{

	public static function findByPidAndFinished($pid = null, $finished = false, $loadStatusses = false) {
		$query = Doctrine_Query::create()
				->from('Work w');
				
		if(null === $pid) $query->where('w.current_pid IS NULL');
		else $query->where('w.current_pid = ?', $pid);
		
		if(null !== $finished) $query->andWhere('w.finished = ?', $finished);

		if($loadStatusses) {
			$query->leftJoin('w.StatusLines s');
		}
		return $query->execute();
	}
	
	public static function findAll() {
		$query = Doctrine_Query::create()
		->from('Work w');
		return $query->execute();
	}
	
	public static function setWorksToPid($pid, $max, $excludeWorks = null) {
		$query = Doctrine_Query::create()
				 ->update('Work w')
				 ->set('w.current_pid', '?', $pid)
				 ->where('w.current_pid IS NULL')
				 ->andWhere('finished = ?', false);
		
		if(!is_null($excludeWorks) && !empty($excludeWorks)) 
			$query->andWhereNotIn('w.id', $excludeWorks);
		

		$query->limit($max);
		return $query->execute();
	}
	
	public function getLastStatusLine() {
		$query = Doctrine_Query::create()
				 ->from('StatusLine s')
				 ->where('s.id = (SELECT MAX(s2.id) FROM StatusLine s2 WHERE s2.work_id = ?)', $this->id);
		
		
		return $query->fetchOne();
//		return count($result) > 0 ? $result[0] : false;
	}

}